apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tradeflow-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.className | default "haproxy" }}
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-ext
  # We deploy this service into the namespace where the pods are
  namespace: haproxy-controller 
spec:
  type: NodePort
  selector:
    # These match the labels found in your 'kubectl get pods' output
    app.kubernetes.io/instance: haproxy-gateway
    app.kubernetes.io/name: haproxy-unified-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.gateway.nodePort }}