apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user.fullname" . }}-config
  labels:
    {{- include "user.selectorLabels" . | nindent 4 }}
data:
  MONGO_URI: {{ .Values.env.MONGO_URI | quote }}