apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user.fullname" . }}-secret
type: Opaque
stringData:
  # Example (if needed later)
  # MONGO_PASSWORD: {{ .Values.env.MONGO_PASSWORD | quote }}