architecture: replicaset

replicaCount: 3

image:
  repository: bitnami/mongodb
  tag: 7.0
  pullPolicy: IfNotPresent

replicaSetName: rs0

persistence:
  storageClass: nfs-storage
  size: 10Gi

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 5