architecture: replicaset

replicaCount: 3

image:
  repository: bitnami/mongodb
  tag: 7.0
  pullPolicy: IfNotPresent

auth:
  enabled: false

replicaSetName: rs0

service:
  nameOverride: mongodb

persistence:
  enabled: true
  storageClass: nfs-storage
  size: 10Gi

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

startupProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 30

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 5