global:
  environment: prod
  ingress:
    domain: tradeflow.com

frontend:
  replicaCount: 3
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

user:
  replicaCount: 3
  resources:
    limits:
      cpu: "400m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

stock:
  replicaCount: 3
  resources:
    limits:
      cpu: "400m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

trading:
  replicaCount: 3
  resources:
    limits:
      cpu: "400m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

portfolio:
  replicaCount: 3
  resources:
    limits:
      cpu: "400m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

# =========================
# MONGODB (BITNAMI STYLE)
# =========================
mongodb:
  architecture: replicaset

  replicaCount: 3

  auth:
    enabled: false

  replicaSetName: rs0

  persistence:
    enabled: true
    storageClass: nfs-storage
    size: 20Gi

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"