global:
  environment: dev
  ingress:
    domain: dev.tradeflow.local

frontend:
  replicaCount: 2
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

user:
  replicaCount: 2
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

stock:
  replicaCount: 2
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

trading:
  replicaCount: 2
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

portfolio:
  replicaCount: 2
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

# =========================
# MONGODB (BITNAMI STYLE)
# =========================
mongodb:
  replicaCount: 3

  replicaSetName: rs0

  persistence:
    storageClass: nfs-storage
    size: 5Gi

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"