global:
  environment: default
  ingress:
    domain: tradeflow.local

# -------------------------
# MICROSERVICES DEFAULTS
# -------------------------
frontend:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: "300m"
      memory: "256Mi"
    requests:
      cpu: "150m"
      memory: "128Mi"

user:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: "300m"
      memory: "256Mi"
    requests:
      cpu: "150m"
      memory: "128Mi"
  env:
    MONGO_URI: mongodb://tradeflow-mongodb-0.tradeflow-mongodb-headless:27017,tradeflow-mongodb-1.tradeflow-mongodb-headless:27017,tradeflow-mongodb-2.tradeflow-mongodb-headless:27017/user-db?replicaSet=rs0


stock:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: "300m"
      memory: "256Mi"
    requests:
      cpu: "150m"
      memory: "128Mi"

trading:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: "300m"
      memory: "256Mi"
    requests:
      cpu: "150m"
      memory: "128Mi"

portfolio:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: "300m"
      memory: "256Mi"
    requests:
      cpu: "150m"
      memory: "128Mi"

mongodb:
  enabled: true

gateway:
  enabled: true

haproxy:
  enabled: true