global:
  environment: prod
  ingress:
    domain: tradeflow.com

# -------------------------
# FRONTEND
# -------------------------
frontend:
  replicaCount: 3
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

# -------------------------
# MICROSERVICES
# -------------------------
user:
  replicaCount: 3
  resources:
    limits:
      cpu: "400m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

stock:
  replicaCount: 3
  resources:
    limits:
      cpu: "400m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

trading:
  replicaCount: 3
  resources:
    limits:
      cpu: "400m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

portfolio:
  replicaCount: 3
  resources:
    limits:
      cpu: "400m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

# -------------------------
# MONGODB
# -------------------------
mongodb:
  replicaCount: 3
  storage:
    size: 20Gi