global:
  environment: dev
  ingress:
    domain: dev.tradeflow.local

frontend:
  replicaCount: 2
  image:
    repository: thamizhanm3/tradeflow-frontend
    tag: "v0.0.3"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
  env:
    VITE_USERS_API: "http://tradeflow-dev-user.tradeflow-dev.svc.cluster.local:4001"
    VITE_STOCKS_API: "http://tradeflow-dev-stock.tradeflow-dev.svc.cluster.local:4002"
    VITE_TRADES_API: "http://tradeflow-dev-trading.tradeflow-dev.svc.cluster.local:4003"
    VITE_PORTFOLIO_API: "http://tradeflow-dev-portfolio.tradeflow-dev.svc.cluster.local:4004"

user:
  replicaCount: 2
  image:
    repository: thamizhanm3/tradeflow-user
    tag: "v0.0.1"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
  env:
    MONGODB_URI: "mongodb://tradeflow-dev-mongodb-0.tradeflow-dev-mongodb-headless:27017,tradeflow-dev-mongodb-1.tradeflow-dev-mongodb-headless:27017,tradeflow-dev-mongodb-2.tradeflow-dev-mongodb-headless:27017/user-db?replicaSet=rs0"
    PORT: "4001"


stock:
  replicaCount: 2
  image:
    repository: thamizhanm3/tradeflow-stock
    tag: "v0.0.1"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
  env:
    MONGODB_URI: "mongodb://tradeflow-dev-mongodb-0.tradeflow-dev-mongodb-headless:27017,tradeflow-dev-mongodb-1.tradeflow-dev-mongodb-headless:27017,tradeflow-dev-mongodb-2.tradeflow-dev-mongodb-headless:27017/user-db?replicaSet=rs0"
    PORT: "4002"

trading:
  replicaCount: 2
  image:
    repository: thamizhanm3/tradeflow-trading
    tag: "v0.0.1"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
  env:
    MONGODB_URI: "mongodb://tradeflow-dev-mongodb-0.tradeflow-dev-mongodb-headless:27017,tradeflow-dev-mongodb-1.tradeflow-dev-mongodb-headless:27017,tradeflow-dev-mongodb-2.tradeflow-dev-mongodb-headless:27017/user-db?replicaSet=rs0"
    PORT: "4003"

portfolio:
  replicaCount: 2
  image:
    repository: thamizhanm3/tradeflow-portfolio
    tag: "v0.0.1"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
  env:
    MONGODB_URI: "mongodb://tradeflow-dev-mongodb-0.tradeflow-dev-mongodb-headless:27017,tradeflow-dev-mongodb-1.tradeflow-dev-mongodb-headless:27017,tradeflow-dev-mongodb-2.tradeflow-dev-mongodb-headless:27017/user-db?replicaSet=rs0"
    PORT: "4004"

mongodb:
  architecture: replicaset
  replicaCount: 3
  auth:
    enabled: false
  replicaSetName: rs0
  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClass: nfs-storage
    size: 5Gi
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"
  arbiter:
    enabled: false
    image:
      registry: docker.io
      repository: bitnami/mongodb
      tag: latest
    resources:
      limits:
        cpu: "250m"
        memory: "512Mi"
      requests:
        cpu: "150m"
        memory: "256Mi"