global:
  environment: default
  ingress:
    domain: tradeflow.local

# -------------------------
# MICROSERVICES DEFAULTS
# -------------------------
frontend:
  enabled: true
  probes:
    path: /
    failureThreshold: 30
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 80
  env:
    PORT: "80"

user:
  enabled: true
  probes:
    path: /health
    failureThreshold: 30
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 4001
  env:
    PORT: "4001"
  routePath: "/api/users"

stock:
  enabled: true
  probes:
    path: /health
    failureThreshold: 30
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 4002
  env:
    PORT: "4002"
  routePath: "/api/stocks"

trading:
  enabled: true
  probes:
    path: /health
    failureThreshold: 30
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 4003
  env:
    PORT: "4003"
  routePath: "/api/trades"

portfolio:
  enabled: true
  probes:
    path: /health
    failureThreshold: 30
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 4004
  env:
    PORT: "4004"
  routePath: "/api/portfolio"

mongodb:
  enabled: true

gateway:
  enabled: true

haproxy:
  enabled: true