# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ include "mongodb.fullname" . }}-init
#   labels:
#     {{- include "mongodb.selectorLabels" . | nindent 4 }}
# data:
#   init.sh: |
#     #!/bin/bash
    
#     if [ "${HOSTNAME}" == "{{ include "mongodb.fullname" . }}-0" ]; then
#       echo "Waiting for MongoDB to start..."
#       sleep 10
#       echo "Initializing Replica Set rs0..."
#       mongosh --eval "rs.initiate({_id: 'rs0', members: [
#         {_id: 0, host: '{{ include "mongodb.fullname" . }}-0.{{ include "mongodb.fullname" . }}-headless:27017'},
#         {_id: 1, host: '{{ include "mongodb.fullname" . }}-1.{{ include "mongodb.fullname" . }}-headless:27017'},
#         {_id: 2, host: '{{ include "mongodb.fullname" . }}-2.{{ include "mongodb.fullname" . }}-headless:27017'}
#       ]})"
      
#       echo "Creating microservice databases..."
#       mongosh --eval "use user-db; db.createCollection('users');"
#       mongosh --eval "use stock-db; db.createCollection('stocks');"
#       mongosh --eval "use trading-db; db.createCollection('trades');"
#       mongosh --eval "use portfolio-db; db.createCollection('portfolios');"
#     else
#       echo "Not primary, skipping init."
#     fi
