apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crop-advisory-service-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: smartharvest
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Smart-Harvest/SmartHarvest-HelmCharts.git
    targetRevision: HEAD
    path: microservices/crop-advisory-service
    helm:
      valueFiles:
        - ../../values/values.yaml
        - ../../values/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tradeflow-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tradeflow
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Thamizhan-M3/Tradeflow-Kubernetes-Manifests.git
    targetRevision: HEAD
    path: helm/tradeflow
    helm:
      valueFiles:
        - ../../values/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tradeflow-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tradeflow-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tradeflow
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Thamizhan-M3/Tradeflow-Kubernetes-Manifests.git
    targetRevision: HEAD
    path: helm/tradeflow
    helm:
      valueFiles:
        - ../../values/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tradeflow-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true