apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
# CHANGE THIS LINE:
provisioner: cluster.local/nfs-client-nfs-subdir-external-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - hard
  - timeo=600
  - retrans=2