replicaCount: 2

image:
  repository: thamizhanm3/tradeflow-user
  tag: "v0.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4001

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

probes:
  liveness:
    path: /health
    port: 4001
  readiness:
    path: /health
    port: 4001
  startup:
    path: /health
    port: 4001
    failureThreshold: 30
    periodSeconds: 10
