apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.env.PORT }}
      protocol: TCP
      name: http
      nodePort: 30105
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
