apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "trading.fullname" . }}-route
spec:
  parentRefs:
    - name: tradeflow-gateway
  rules:
    - matches:
        - path:
            type: Prefix
            value: {{ .Values.routePath }}
      backendRefs:
        - name: {{ include "trading.fullname" . }}
          port: {{ .Values.service.port }}
